name: test-docker-windows

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest
    env:
      UV_CACHE_DIR: .uv-cache
      UV_LINK_MODE: copy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .uv-cache
          key: default
  
      - run: pwd
      - run: pip install uv -q
      - run: uv venv
      - run: .venv\Scripts\activate
      - run: uv pip install ruff -v
      # - run: ruff --version  # Not working for some reason...
      - run: uv cache prune --ci
      
      - if: success()
        uses: actions/cache@v3
        with:
          path: .uv-cache
          key: default
